apiVersion: apps/v1
kind: Deployment
metadata:
    name: carrental-deployment
    labels:
      app: carrental
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carrental
  template:
    metadata:
      labels:
        app: carrental
    spec:
      serviceAccountName: carrental
      containers:
      - name: carrental
        image: tiagomadeiradock/railscarrentalsapi:dd8e653
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
          - name: http
            containerPort: 3000
        env:
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: carrental-k8s-secret
                key: k8s-rails-master-key
          - name: DEVISE_JWT_SECRET_KEY 
            valueFrom:
              secretKeyRef:
                name: carrental-k8s-secret
                key: k8s-devise-jwt-secret-key
          - name: POSTGRES_URL
            valueFrom:
             configMapKeyRef:
                name: carrental-configmap
                key: database_url
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: carrental-aws-secrets           
---
apiVersion: v1
kind: Service
metadata:
  name: carrental-internal-service
spec:
  selector:
    app: carrental
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
