apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carrental
spec:
  ingressClassName: external-nginx
  rules:
  - host: k8s-ingress-external-c1290dec7a-968360f4e1f59017.elb.eu-west-3.amazonaws.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: carrental-internal-service
            port: 
              number: 3000
