apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: carrental-aws-secrets
spec:
  provider: aws

  parameters: 
    region: eu-west-3
    objects: |
      - objectName: "staging/carrental-secret"
        objectType: "secretsmanager"
        jmesPath:
            - path: RAILS_MASTER_KEY
              objectAlias: rails-master-key
            - path: DEVISE_JWT_SECRET_KEY
              objectAlias: devise-jwt-secret-key

      - objectName: "staging/carrental-db-secret"
        objectType: "secretsmanager"
        jmesPath:
            - path: TEST_USER
              objectAlias: test-user
            - path: TEST_PASS
              objectAlias: test-pass
    usePodIdentity: "true"          
  secretObjects: 
    - secretName: carrental-k8s-secret
      type: Opaque
      data:
        - objectName: rails-master-key
          key: k8s-rails-master-key
        - objectName: devise-jwt-secret-key
          key: k8s-devise-jwt-secret-key

    - secretName: carrental-db-k8s-secret
      type: Opaque
      data:
        - objectName: test-user
          key: k8s-test-user
        - objectName: test-pass
          key: k8s-test-pass