apiVersion: v1
kind: ConfigMap
metadata:
  name: carrental-configmap
data:
  database_name: StagingCarrentalDb
  database_host: terraform-20260317123942285600000004.ctsik20mstcl.eu-west-3.rds.amazonaws.com