apiVersion: v1
kind: ConfigMap
metadata:
  name: carrental-configmap
data:
  database_name: StagingCarrentalDb
  database_host: terraform-20251121120829785800000001.ctsik20mstcl.eu-west-3.rds.amazonaws.com